export default {
	GET_ALL_ARTICLES:'GET_ALL_ARTICLES',
	GET_ALL_CATEGORIES:'GET_ALL_CATEGORIES',
	ADD_NEW_ARTICLE :'ADD_NEW_ARTICLE',
	REMOVE_ARTICLE:'REMOVE_ARTICLE',

	UPDATE_ARTICLE:'UPDATE_ARTICLE',
	GET_UPDATED_DATA:'GET_UPDATED_DATA',
	GET_UPDATED_CATS:'GET_UPDATED_CATS',
}